using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BmsAtelierKyokufu.BmsPartTuner.Generators
{
    public record struct LoggableTypeInfo(string FullyQualifiedName, string SimpleName);

    [Generator]
    public class LogTagGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var typeDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static t => t != null);

            var collectedTypes = typeDeclarations.Collect();

            context.RegisterSourceOutput(collectedTypes, static (spc, types) => Execute(spc, types));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax || node is StructDeclarationSyntax || node is RecordDeclarationSyntax;
        }

        private static LoggableTypeInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var typeDecl = (TypeDeclarationSyntax)context.Node;

            if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol) return null;

            // Skip private, generic, static, or ref-like types
            if (symbol.DeclaredAccessibility == Accessibility.Private) return null;
            if (symbol.IsGenericType) return null;
            if (symbol.IsStatic) return null;
            if (symbol.IsRefLikeType) return null;

            // Check if nested in a generic or private type
            var parent = symbol.ContainingType;
            while (parent != null)
            {
                if (parent.IsGenericType) return null;
                if (parent.DeclaredAccessibility == Accessibility.Private) return null;
                parent = parent.ContainingType;
            }

            string fullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string simpleName = symbol.Name;

            return new LoggableTypeInfo(fullyQualifiedName, simpleName);
        }

        private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<LoggableTypeInfo?> types)
        {
            if (types.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace BmsAtelierKyokufu.BmsPartTuner.Generators");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class LogTagInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");

            var processedTypes = new HashSet<string>();

            foreach (var typeInfoOpt in types)
            {
                if (typeInfoOpt is not { } typeInfo) continue;
                if (!processedTypes.Add(typeInfo.FullyQualifiedName)) continue;

                sb.AppendLine($"            global::BmsAtelierKyokufu.BmsPartTuner.Core.Helpers.LogTagCache<{typeInfo.FullyQualifiedName}>.Tag = \"{typeInfo.SimpleName}\";");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("LogTagInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
