using Microsoft.Win32;
namespace BmsAtelierKyokufu.BmsPartTuner.UI.ViewModels;

/// <summary>
/// BMSファイルの入力・出力パスの管理とファイル選択ダイアログの制御を行うViewModel。
/// 出力パスの自動生成や上書き確認などの責務を持ちます。
/// </summary>
public partial class FileOperationsViewModel : ObservableObject
{
    /// <summary>
    /// 最適化対象のBMS/bmsonファイルの入力パス。
    /// </summary>
    [ObservableProperty]
    public partial string InputPath { get; set; } = string.Empty;

    /// <summary>
    /// 最適化後のBMSファイルの出力パス。
    /// </summary>
    [ObservableProperty]
    public partial string OutputPath { get; set; } = string.Empty;

    private string? _lastAutoGeneratedOutputPath;
    private string _lastProcessedInputPath = string.Empty;

    /// <summary>
    /// 入力パスが変更され、有効なファイルであることが確認された際に発生するイベント。
    /// </summary>
    public event EventHandler<string>? InputPathChanged;

    /// <summary>
    /// 出力パスが自動生成された際に発生するイベント。
    /// </summary>
    public event EventHandler<string>? AutoOutputPathRequested;

    partial void OnInputPathChanged(string value)
    {
        var path = value.Trim('"');

        if (File.Exists(path) && IsSupportedBmsFile(path))
        {
            InputPathChanged?.Invoke(this, path);
            WeakReferenceMessenger.Default.Send(new InputPathChangedMessage(path));

            if (ShouldAutoSetOutputPath())
            {
                string? directory = Path.GetDirectoryName(path);
                var extension = Path.GetExtension(path);
                if (string.Equals(extension, ".bmson", StringComparison.OrdinalIgnoreCase))
                {
                    extension = ".bms";
                }
                var baseFileName = Path.GetFileNameWithoutExtension(path);
                var fileName = $"{baseFileName}{AppConstants.Files.OptimizedFileSuffix}{extension}";
                var autoPath = Path.Combine(directory ?? string.Empty, fileName);
                _lastAutoGeneratedOutputPath = autoPath;

                AutoOutputPathRequested?.Invoke(this, autoPath);
                WeakReferenceMessenger.Default.Send(new AutoOutputPathRequestedMessage(autoPath));
            }

            _lastProcessedInputPath = path;
        }
    }

    [RelayCommand]
    private void BrowseInputFile()
    {
        var dialog = new OpenFileDialog
        {
            Filter = $"BMS/BMSONファイル ({GetDialogExtensionPattern()})|{GetDialogExtensionPattern()}|すべてのファイル (*.*)|*.*",
            Title = "BMS/BMSONファイルを選択"
        };

        if (dialog.ShowDialog() is true)
        {
            InputPath = dialog.FileName;
        }
    }

    [RelayCommand]
    private void BrowseOutputFile()
    {
        var dialog = new SaveFileDialog
        {
            Filter = $"BMSファイル ({GetOutputDialogExtensionPattern()})|{GetOutputDialogExtensionPattern()}|すべてのファイル (*.*)|*.*",
            FileName = AppConstants.Files.DefaultOutputFileName,
            Title = "保存先を選択",
            DefaultExt = ".bms"
        };

        if (dialog.ShowDialog() is true)
        {
            OutputPath = dialog.FileName;
        }
    }

    private bool ShouldAutoSetOutputPath()
    {
        var currentInput = InputPath?.Trim('"') ?? string.Empty;
        var currentOutput = OutputPath?.Trim('"') ?? string.Empty;

        try
        {
            if (string.IsNullOrWhiteSpace(currentOutput) ||
                !Directory.Exists(Path.GetDirectoryName(Path.GetFullPath(currentOutput))))
            {
                return true;
            }
        }
        catch (Exception ex) when (ex is ArgumentException || ex is NotSupportedException || ex is PathTooLongException)
        {
            return true;
        }

        if (currentOutput == _lastAutoGeneratedOutputPath)
        {
            return true;
        }

        static bool isSameDirectory(string path1, string path2) =>
            string.Equals(
                Path.GetDirectoryName(path1),
                Path.GetDirectoryName(path2),
                StringComparison.OrdinalIgnoreCase
            );

        return string.IsNullOrEmpty(_lastProcessedInputPath) ||
           !isSameDirectory(currentInput, _lastProcessedInputPath);
    }

    private static bool IsSupportedBmsFile(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLower();
        return Array.Exists(AppConstants.Files.SupportedBmsExtensions, ext => ext == extension);
    }

    private static string GetDialogExtensionPattern()
    {
        return string.Join(";", Array.ConvertAll(AppConstants.Files.SupportedBmsExtensions, static ext => $"*{ext}"));
    }

    private static string GetOutputDialogExtensionPattern()
    {
        return string.Join(";", Array.ConvertAll(AppConstants.Files.SupportedOutputBmsExtensions, static ext => $"*{ext}"));
    }

    /// <summary>
    /// 現在指定されている出力パスのファイルが既に存在し、上書き確認が必要かどうかを判定します。
    /// </summary>
    public bool CheckOverwriteRequired()
    {
        var outputPath = OutputPath.Trim('"');
        return File.Exists(outputPath);
    }

    /// <summary>
    /// 指定されたファイルパスの拡張子に対応する表示用のファイルタイプ名を取得します。
    /// </summary>
    public static string GetFileTypeName(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLower();
        return AppConstants.Files.GetFileTypeName(extension);
    }
}
