using BmsAtelierKyokufu.BmsPartTuner.Core;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Win32;

namespace BmsAtelierKyokufu.BmsPartTuner.ViewModels;

/// <summary>
/// ファイル操作ViewModel。
/// </summary>
/// <remarks>
/// <para>【責務】</para>
/// <list type="bullet">
/// <item>入力BMSファイルの選択とパス管理</item>
/// <item>出力ファイルのパス管理と自動生成</item>
/// <item>ファイルダイアログの制御</item>
/// <item>上書き確認の判定</item>
/// </list>
/// 
/// <para>【出力パスの自動生成ロジック】</para>
/// 入力パスが変更された際、以下の条件で出力パスを自動設定:
/// <list type="number">
/// <item>出力パスが空または無効なディレクトリ</item>
/// <item>出力パスが前回の自動生成パスと一致（ユーザーが手動変更していない）</item>
/// <item>入力ファイルのディレクトリが変更された</item>
/// </list>
/// 
/// <para>【自動生成パターン】</para>
/// 入力: "song.bms" → 出力: "song_optimized.bms"
/// サフィックス（<see cref="AppConstants.OptimizedFileSuffix"/>）を付加します。
/// 
/// <para>【Why 自動生成】</para>
/// ユーザーが毎回出力パスを指定する手間を省き、
/// 一般的なユースケース（同じディレクトリに保存）をサポートします。
/// </remarks>
public partial class FileOperationsViewModel : ObservableObject
{
    [ObservableProperty]
    private string _inputPath = string.Empty;

    [ObservableProperty]
    private string _outputPath = string.Empty;

    private string? _lastAutoGeneratedOutputPath;
    private string _lastProcessedInputPath = string.Empty;

    /// <summary>入力パス変更イベント。</summary>
    public event EventHandler<string>? InputPathChanged;

    /// <summary>自動出力パス要求イベント。</summary>
    public event EventHandler<string>? AutoOutputPathRequested;

    /// <summary>
    /// 入力パス変更時の処理。
    /// </summary>
    /// <param name="value">新しい入力パス。</param>
    /// <remarks>
    /// <para>【処理フロー】</para>
    /// <list type="number">
    /// <item>パスのトリム（引用符除去）</item>
    /// <item>ファイルの存在とサポート形式のチェック</item>
    /// <item><see cref="InputPathChanged"/>イベントを発火</item>
    /// <item>出力パスの自動設定（条件を満たす場合）</item>
    /// </list>
    /// </remarks>
    partial void OnInputPathChanged(string value)
    {
        var path = value.Trim('"');

        if (File.Exists(path) && IsSupportedBmsFile(path))
        {
            InputPathChanged?.Invoke(this, path);

            if (ShouldAutoSetOutputPath())
            {
                string? directory = Path.GetDirectoryName(path);
                var extension = Path.GetExtension(path);
                var baseFileName = Path.GetFileNameWithoutExtension(path);
                var fileName = $"{baseFileName}{AppConstants.Files.OptimizedFileSuffix}{extension}";
                var autoPath = Path.Combine(directory ?? string.Empty, fileName);
                _lastAutoGeneratedOutputPath = autoPath;

                AutoOutputPathRequested?.Invoke(this, autoPath);
            }

            _lastProcessedInputPath = path;
        }
    }

    /// <summary>
    /// 入力ファイルを参照。
    /// </summary>
    /// <remarks>
    /// OpenFileDialogを表示し、ユーザーがファイルを選択すると
    /// <see cref="InputPath"/>に設定されます。
    /// </remarks>
    [RelayCommand]
    private void BrowseInputFile()
    {
        var dialog = new OpenFileDialog
        {
            Filter = $"BMSファイル ({GetDialogExtensionPattern()})|{GetDialogExtensionPattern()}|すべてのファイル (*.*)|*.*",
            Title = "BMSファイルを選択"
        };

        if (dialog.ShowDialog() == true)
        {
            InputPath = dialog.FileName;
        }
    }

    /// <summary>
    /// 出力ファイルを参照。
    /// </summary>
    /// <remarks>
    /// SaveFileDialogを表示し、ユーザーがファイルを選択すると
    /// <see cref="OutputPath"/>に設定されます。
    /// </remarks>
    [RelayCommand]
    private void BrowseOutputFile()
    {
        var dialog = new SaveFileDialog
        {
            Filter = $"BMSファイル ({GetDialogExtensionPattern()})|{GetDialogExtensionPattern()}|すべてのファイル (*.*)|*.*",
            FileName = AppConstants.Files.DefaultOutputFileName,
            Title = "保存先を選択",
            DefaultExt = ".bms"
        };

        if (dialog.ShowDialog() == true)
        {
            OutputPath = dialog.FileName;
        }
    }

    /// <summary>
    /// 出力パスを自動設定すべきかを判定。
    /// </summary>
    /// <returns>自動設定すべき場合true。</returns>
    /// <remarks>
    /// <para>【判定条件】</para>
    /// <list type="bullet">
    /// <item>出力パスが空または無効</item>
    /// <item>出力パスが前回の自動生成パスと一致</item>
    /// <item>入力ファイルのディレクトリが変更された</item>
    /// </list>
    /// 
    /// <para>【Why この判定】</para>
    /// ユーザーが手動で出力パスを変更した場合は、
    /// それを尊重して上書きしないようにします。
    /// </remarks>
    private bool ShouldAutoSetOutputPath()
    {
        var currentInput = InputPath?.Trim('"') ?? string.Empty;
        var currentOutput = OutputPath?.Trim('"') ?? string.Empty;

        try
        {
            if (string.IsNullOrWhiteSpace(currentOutput) ||
                !Directory.Exists(Path.GetDirectoryName(Path.GetFullPath(currentOutput))))
            {
                return true;
            }
        }
        catch (Exception ex) when (ex is ArgumentException || ex is NotSupportedException || ex is PathTooLongException)
        {
            return true;
        }

        if (currentOutput == _lastAutoGeneratedOutputPath)
        {
            return true;
        }

        var isSameDirectory = (string path1, string path2) =>
            string.Equals(
                Path.GetDirectoryName(path1),
                Path.GetDirectoryName(path2),
                StringComparison.OrdinalIgnoreCase
            );

        return string.IsNullOrEmpty(_lastProcessedInputPath) ||
           !isSameDirectory(currentInput, _lastProcessedInputPath);
    }

    /// <summary>
    /// サポートされているBMSファイルかをチェック。
    /// </summary>
    /// <param name="filePath">ファイルパス。</param>
    /// <returns>サポートされている場合true。</returns>
    private bool IsSupportedBmsFile(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLower();
        return Array.Exists(AppConstants.Files.SupportedBmsExtensions, ext => ext == extension);
    }

    /// <summary>
    /// ダイアログ用の拡張子パターンを取得。
    /// </summary>
    /// <returns>ワイルドカードパターン（例: "*.bms;*.bme;*.bml"）。</returns>
    private string GetDialogExtensionPattern()
    {
        return string.Join(";", Array.ConvertAll(AppConstants.Files.SupportedBmsExtensions, ext => $"*{ext}"));
    }

    /// <summary>
    /// 上書き確認が必要かをチェック。
    /// </summary>
    /// <returns>出力ファイルが既に存在する場合true。</returns>
    public bool CheckOverwriteRequired()
    {
        var outputPath = OutputPath.Trim('"');
        return File.Exists(outputPath);
    }

    /// <summary>
    /// ファイルタイプ名を取得。
    /// </summary>
    /// <param name="filePath">ファイルパス。</param>
    /// <returns>ファイルタイプ名（例: "BMS", "BME"）。</returns>
    public string GetFileTypeName(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLower();
        return AppConstants.Files.GetFileTypeName(extension);
    }
}
